// <auto-generated />
using System;
using AssTrack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AssTrackDbContext))]
    [Migration("20260507232939_AddAssetCustody")]
    partial class AddAssetCustody
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("AssTrack.Domain.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("property");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("normal");

                    b.Property<string>("CustodianContact")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustodianName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CustodySince")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustodyStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("available");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpeedThresholdKmh")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.CustodyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCustodianName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCustodianContact")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCustodianName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("AssetId", "OccurredAt");

                    b.ToTable("CustodyEvents");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IntegrationFeedId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual");

                    b.Property<string>("ProviderHardwareModel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLongName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProviderProfileUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderRole")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderShortName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("IntegrationFeedId", "ExternalId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.DeviceGeofenceState", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GeofenceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInside")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastObservationAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId", "GeofenceId");

                    b.HasIndex("GeofenceId");

                    b.ToTable("DeviceGeofenceStates");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.Geofence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolygonJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("circle");

                    b.HasKey("Id");

                    b.ToTable("Geofences");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.GeofenceBreach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("GeofenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("GeofenceId");

                    b.HasIndex("ObservationId");

                    b.HasIndex("DeviceId", "DetectedAt");

                    b.ToTable("GeofenceBreaches");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.IntegrationFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoCreateDevices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.ToTable("IntegrationFeeds");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MaintenanceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IntervalOdometerKm")
                        .HasColumnType("REAL");

                    b.Property<double?>("IntervalRuntimeHours")
                        .HasColumnType("REAL");

                    b.Property<double?>("LastOdometerKm")
                        .HasColumnType("REAL");

                    b.Property<double?>("LastRuntimeHours")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastServiceAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("general");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ServiceType");

                    b.ToTable("MaintenanceSchedules");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MaintenanceServiceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaintenanceScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("OdometerKm")
                        .HasColumnType("REAL");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RuntimeHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "CompletedAt");

                    b.HasIndex("MaintenanceScheduleId", "CompletedAt");

                    b.ToTable("MaintenanceServiceRecords");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MessageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderMessageId");

                    b.HasIndex("ThreadId", "CreatedAt");

                    b.HasIndex("Status", "Direction", "CreatedAt");

                    b.ToTable("MessageEntries");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MessageThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPeerId")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IntegrationFeedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("open");

                    b.Property<string>("Subject")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("IntegrationFeedId", "ExternalPeerId");

                    b.HasIndex("Provider", "ExternalPeerId");

                    b.ToTable("MessageThreads");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("REAL");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HeadingDegrees")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpeedKmh")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt");

                    b.HasIndex("DeviceId", "ObservedAt")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IntegrationFeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationFeedId");

                    b.HasIndex("SensorType");

                    b.HasIndex("AssetId", "ObservedAt");

                    b.HasIndex("DeviceId", "ObservedAt");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.SpeedAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ObservedSpeedKmh")
                        .HasColumnType("REAL");

                    b.Property<double>("ThresholdKmh")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ObservationId");

                    b.HasIndex("DeviceId", "TriggeredAt");

                    b.ToTable("SpeedAlerts");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.WebhookDeliveryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestPayloadSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType");

                    b.ToTable("WebhookDeliveryLogs");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.CustodyEvent", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany("CustodyEvents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.Device", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany("Devices")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssTrack.Domain.Models.IntegrationFeed", "IntegrationFeed")
                        .WithMany("Devices")
                        .HasForeignKey("IntegrationFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("IntegrationFeed");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.DeviceGeofenceState", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssTrack.Domain.Models.Geofence", "Geofence")
                        .WithMany()
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Geofence");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.GeofenceBreach", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssTrack.Domain.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssTrack.Domain.Models.Geofence", "Geofence")
                        .WithMany()
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssTrack.Domain.Models.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Device");

                    b.Navigation("Geofence");

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MaintenanceSchedule", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MaintenanceServiceRecord", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany("MaintenanceServiceRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssTrack.Domain.Models.MaintenanceSchedule", "MaintenanceSchedule")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("MaintenanceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("MaintenanceSchedule");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MessageEntry", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.MessageThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MessageThread", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssTrack.Domain.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssTrack.Domain.Models.IntegrationFeed", "IntegrationFeed")
                        .WithMany()
                        .HasForeignKey("IntegrationFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Device");

                    b.Navigation("IntegrationFeed");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.Observation", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Device", "Device")
                        .WithMany("Observations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.SensorReading", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany("SensorReadings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssTrack.Domain.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssTrack.Domain.Models.IntegrationFeed", "IntegrationFeed")
                        .WithMany()
                        .HasForeignKey("IntegrationFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Device");

                    b.Navigation("IntegrationFeed");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.SpeedAlert", b =>
                {
                    b.HasOne("AssTrack.Domain.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssTrack.Domain.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssTrack.Domain.Models.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Device");

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.Asset", b =>
                {
                    b.Navigation("CustodyEvents");

                    b.Navigation("Devices");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("MaintenanceServiceRecords");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.Device", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.IntegrationFeed", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MaintenanceSchedule", b =>
                {
                    b.Navigation("ServiceRecords");
                });

            modelBuilder.Entity("AssTrack.Domain.Models.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
