// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AssTrack.E2ETests.Features
{


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CoreFlowsFeature : object, global::Xunit.IClassFixture<CoreFlowsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {

        private global::Reqnroll.ITestRunner testRunner;

        private static string[] featureTags = ((string[])(null));

        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Core Flows", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());

        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "CoreFlows.feature"
#line hidden

        public CoreFlowsFeature(CoreFlowsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }

        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }

        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }

        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null)
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null)
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }

        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }

        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }

        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }

        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
  await testRunner.GivenAsync("an asset named \"E2E Test Asset\" exists via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
  await testRunner.AndAsync("a device with identifier \"E2E-DEVICE-001\" is linked to the asset", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }

        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CoreFlows.feature.ndjson", 14);
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Create an observation for an asset")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "Create an observation for an asset")]
        public async global::System.Threading.Tasks.Task CreateAnObservationForAnAsset()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create an observation for an asset", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 8
  await testRunner.WhenAsync("I post an observation for the device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
  await testRunner.AndAsync("I navigate to the assets page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
  await testRunner.ThenAsync("the page contains \"E2E Test Asset\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="View asset details")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "View asset details")]
        public async global::System.Threading.Tasks.Task ViewAssetDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View asset details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 13
  await testRunner.WhenAsync("I navigate to the assets page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
  await testRunner.ThenAsync("the page contains \"E2E Test Asset\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="View asset maintenance due status")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "View asset maintenance due status")]
        public async global::System.Threading.Tasks.Task ViewAssetMaintenanceDueStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View asset maintenance due status", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 17
  await testRunner.GivenAsync("a due maintenance schedule named \"Mileage inspection\" exists for the asset", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
  await testRunner.WhenAsync("I navigate to the assets page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
  await testRunner.ThenAsync("the page contains \"Maintenance\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
  await testRunner.AndAsync("the page contains \"Mileage inspection\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.AndAsync("the page contains \"due\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Complete due asset maintenance")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "Complete due asset maintenance")]
        public async global::System.Threading.Tasks.Task CompleteDueAssetMaintenance()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Complete due asset maintenance", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 24
  await testRunner.GivenAsync("a due maintenance schedule named \"Mileage inspection\" exists for the asset", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
  await testRunner.WhenAsync("I navigate to the assets page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
  await testRunner.AndAsync("I complete maintenance schedule \"Mileage inspection\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
  await testRunner.ThenAsync("the page contains \"Recent service\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
  await testRunner.AndAsync("the page contains \"current\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="View live map")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "View live map")]
        public async global::System.Threading.Tasks.Task ViewLiveMap()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View live map", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 31
  await testRunner.WhenAsync("I post an observation for the device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
  await testRunner.AndAsync("I navigate to the map page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
  await testRunner.ThenAsync("the page contains \"Live Map\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
  await testRunner.AndAsync("the map layer controls are available", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
  await testRunner.WhenAsync("I select the first map node", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
  await testRunner.ThenAsync("the map node details panel is available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="View geofence authoring controls")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "View geofence authoring controls")]
        public async global::System.Threading.Tasks.Task ViewGeofenceAuthoringControls()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View geofence authoring controls", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 39
  await testRunner.WhenAsync("I navigate to the geofences page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
  await testRunner.ThenAsync("the page contains \"Click the map to set the center.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
  await testRunner.AndAsync("the page contains \"Radius presets\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
  await testRunner.AndAsync("the page contains \"Shape\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="View bridge-created tracking signals")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "View bridge-created tracking signals")]
        public async global::System.Threading.Tasks.Task ViewBridge_CreatedTrackingSignals()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View bridge-created tracking signals", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 45
  await testRunner.GivenAsync("an unassigned bridge device named \"E2E Meshtastic Signal\" exists via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
  await testRunner.WhenAsync("I post an observation for the unassigned bridge device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
  await testRunner.AndAsync("I navigate to the devices page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
  await testRunner.ThenAsync("the page contains \"Tracking signal inbox\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
  await testRunner.AndAsync("the page contains \"E2E Meshtastic Signal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
  await testRunner.AndAsync("the page contains \"Create asset\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="View observations list")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "View observations list")]
        public async global::System.Threading.Tasks.Task ViewObservationsList()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View observations list", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 53
  await testRunner.WhenAsync("I post an observation for the device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
  await testRunner.AndAsync("I navigate to the assets page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
  await testRunner.ThenAsync("the page contains \"E2E Test Asset\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="View alerts with threshold")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "View alerts with threshold")]
        public async global::System.Threading.Tasks.Task ViewAlertsWithThreshold()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View alerts with threshold", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 58
  await testRunner.WhenAsync("I post an observation with speed 150.0 for the device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
  await testRunner.AndAsync("I navigate to the alerts page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
  await testRunner.ThenAsync("the alerts table contains a cell with \"150.0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Filter unacknowledged alerts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "Filter unacknowledged alerts")]
        public async global::System.Threading.Tasks.Task FilterUnacknowledgedAlerts()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter unacknowledged alerts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 63
  await testRunner.WhenAsync("I post an observation with speed 150.0 for the device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
  await testRunner.AndAsync("I navigate to the alerts page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
  await testRunner.ThenAsync("the alerts page has filter tab \"Unacknowledged\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Bulk acknowledge alerts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "Bulk acknowledge alerts")]
        public async global::System.Threading.Tasks.Task BulkAcknowledgeAlerts()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bulk acknowledge alerts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 68
  await testRunner.WhenAsync("I post an observation with speed 150.0 for the device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
  await testRunner.AndAsync("I post an observation with speed 155.0 for the device via the API", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
  await testRunner.AndAsync("I navigate to the alerts page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
  await testRunner.ThenAsync("the alerts page has filter tab \"Unacknowledged\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Configure bridge providers from the main UI")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Core Flows")]
        [global::Xunit.TraitAttribute("Description", "Configure bridge providers from the main UI")]
        public async global::System.Threading.Tasks.Task ConfigureBridgeProvidersFromTheMainUI()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Configure bridge providers from the main UI", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 74
  await testRunner.WhenAsync("I navigate to the bridge page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 75
  await testRunner.AndAsync("I configure bridge provider \"Meshtastic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
  await testRunner.ThenAsync("the bridge feed form is focused with bridge key \"meshtastic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
  await testRunner.AndAsync("the Meshtastic public MQTT defaults are configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
  await testRunner.AndAsync("the bridge checkbox \"Bridge enabled\" is compact", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
  await testRunner.WhenAsync("I configure bridge provider \"Home Assistant\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
  await testRunner.ThenAsync("the bridge feed form is focused with bridge key \"home-assistant\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 81
  await testRunner.AndAsync("the page contains \"Home Assistant location polling\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CoreFlowsFeature.FeatureSetupAsync();
            }

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CoreFlowsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
